version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    groups:
      material-ui:
        patterns:
          - "@mui/*"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
