version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      react-aria:
        patterns:
          - "react-aria"
          - "react-aria-components"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
